# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hs696802/Desktop/square_root/square_root.srcs/sources_1/ip/square_rooter/square_rooter.xci
# IP: The module: 'square_rooter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hs696802/Desktop/square_root/square_root.srcs/sources_1/ip/square_rooter/square_rooter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_rooter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/hs696802/Desktop/square_root/square_root.srcs/sources_1/ip/square_rooter/square_rooter.xci
# IP: The module: 'square_rooter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hs696802/Desktop/square_root/square_root.srcs/sources_1/ip/square_rooter/square_rooter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_rooter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
